### ISSUE TITLE
Issue during setup

### ISSUE THREAD

**Issue by Alnaggar94** [troychaplin79/wp-multitenant#1]
Hello Mr.Troy

First of all, Thank you so much for sharing this project, you saved me so much time and I really appreciate that, I have been going in circles for months trying to make the right Multitenant structure and your project just came like a dream. 
I usually host websites in VPS using popular control panels like cPanel, Plesk, or cloud control panels like Runcloud, GP... That sets everything to give me a nice control interface,  I know the basics of hosting websites and manage them manually I did that when I start learning back in days following tutorials. 

I just create a droplet in Digitalocean to test this project following their article on how to install LAMP stack and install WordPress on it. and sucssfuly did that and then deleted the site and start testing this project as the following:

- Server path: ( `/var/www` )

Containing this folders:  

- `wp-multitenant` ( I tried both the master branch and the developer branch with the latest update you made )
- `domain.com` ( Root of the domain folder )
- `wordpress `( I create this folder and copied the `composer.json` inside it )

I started following your instructions step by step as the following:

(1)
In the Env Vars section, I didn't understand this well, Do you mean the root Mysql user and its password or the new user I normally create when creating a new WordPress database with its user?  I created a database with a user and password and entered that in the .env as below:

![env](https://user-images.githubusercontent.com/49800146/127409301-1fc166f6-f39c-4c6a-8828-cddae9f4b2ab.JPG)

(2)
After renaming and moving the `composer.json` to `/var/www/wordpress` and run composer install I get this error:

![composer sh problem](https://user-images.githubusercontent.com/49800146/127408046-ebb15d0f-c8c2-4a85-aafc-4f532cd665ba.JPG)

(3)
I renamed the `install.example.sh` to `install.sh` and copied it to the root of the domain folder `/var/www/domain.com` , 
Then I edited the copied `install.sh` file and change `path_to_multitenant` on lines 8, 10 and 12 to the `wp-multitenant` folder   `/var/www/wp-multitenant` .

![install sh](https://user-images.githubusercontent.com/49800146/127416719-4251a8e2-4d20-4e79-bbbd-2cf77161940d.JPG)

It asked me 3 questions for the database name I entered the database name I created earlier which I put its username and password in the `.env` file earlier and the domain name `domain.com` and No for multisites.

![final](https://user-images.githubusercontent.com/49800146/127416826-38a0ae49-81be-41e1-a9f1-f2a63377adda.JPG)

--------------------------------------------

Virtual Host: `/etc/apache2/sites-available/natureresult.net.conf` :

```
<VirtualHost *:80>
    ServerName natureresult.net
    ServerAlias www.natureresult.net
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/natureresult.net
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>

<Directory /var/www/wordpress/>
    AllowOverride All
</Directory>
```

When I try to open the site it doesn't work! 

![last](https://user-images.githubusercontent.com/49800146/127417306-a6fc1b69-7643-47ae-8c0b-0b869f68820c.JPG)

I don't know what I have missed,  Could you please see if my steps are correct?

**Comment by Alnaggar94** [comment]
@troychaplin79 -  and this is the apache error log 

![error log](https://user-images.githubusercontent.com/49800146/127648451-3c065e67-0ea0-4c9d-92cd-6ab3ea15628f.JPG)

**Comment by troychaplin** [comment]
Hey @Alnaggar94, I think I see the issue and I just updated the docs based on this. At the start you said you created a `wordpress` folder and copied the `composer.json` into it, that should not be done. The composer file would stay in the `wp-multitenant` folder (or whatever you decide to name it on your server) and would be ran from here as well.

My docs still had references to `wordpress` in there from older version, so this may be why you thought to create the folder and were your problem most likely came from.

Please let me know if you have success with another attempt and I will close this issue.

**Comment by Alnaggar94** [comment]
@troychaplin79 - Thanks for your reply, I have started again with a fresh install and did run the composer install from wp-multitenant and it worked fine without the bash error as before. and this time it almost work and redictred me to the install file when I open the domain but nothing load??

![after](https://user-images.githubusercontent.com/49800146/127692092-ff9e874d-7ef4-41b5-9f38-fa7e1d75d394.JPG)

I think my problem now has something to do with virtual host config setting or permission related?
Could you please share the virtual host config setting? this is the config file I use:

```
<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    ServerName natureresult.net
    ServerAlias www.natureresult.net
    DocumentRoot /var/www/natureresult.net
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>

<Directory /var/www/wordpress/>
      Options FollowSymLinks
      AllowOverride All
      Require all granted
</Directory>
```
and for permission I have tried the following:

```
sudo chown -R sammy:sammy /var/www/natureresult.net
sudo chmod -R 755 /var/www/natureresult.net
sudo chown -R www-data:www-data /var/www/natureresult.net

sudo chown -R sammy:sammy /var/www/wp-multitenant
sudo chmod -R 755 /var/www/wp-multitenant
sudo chown -R www-data:www-data /var/www/wp-multitenant
```

I really appreciate your time and I hope you can help.

**Comment by troychaplin** [comment]
@Alnaggar94 I'm not really a server guy so I can't tell you for sure what could be wrong here. In your virtual host config I see you still have `wordpress` in one of the directory paths, that should be `wp-multitenant`. 

If you could post a screenshot of what you see when you `ls -la` inside both the `wp-multitenant` directory as well as the domain directory I can check those out to make sure they are correct.

I also recently came across an issue on another server where the `open_basedir` was restricted to the domain folder and not allowing php to run outside. Once that was changed to go one level higher the issues from that server were fixed. Not sure if that's your problem or not, but worth a look.

**Comment by Alnaggar94** [comment]
@troychaplin79 - Thanks man for your time I really appreciate your help, it turns out that I forget to change the `Directory /var/www/wordpress` to `Directory /var/www/domain.com` in the virtual host after I change it and reload it works. I also had to install SSL because the CSS files don't load. 

Now it works fine and again thank you so much for sharing this great project and for your time, God bless you.

**Comment by troychaplin** [comment]
Glad to hear it @Alnaggar94, and happy that my personal project can benefit others!
