### ISSUE TITLE
site-config.php is not responding

### ISSUE THREAD

**Issue by avydigital** [troychaplin79/wp-multitenant#4]
Hi thanks for the great work!

I have a question,
I installed exactly as you specified in the README.md file.
I was able to run one site, and it works well.
When I install another site,
Write to me: "It looks like WordPress is already installed. To reinstall you need to delete the old tables from the database."

The site-config.php file defines a different database name from the site that was first installed.
When I rename the file site-config.php,
On the second site,
The WordPress installation is still working.

What did I do wrong?

**Comment by troychaplin** [comment]
Sorry for the very late reply @avydigital, I completely missed this. I can't say for sure what the issue would be, my first guess would be to look at what is set on lines 21 and 31 of each site-config.php, or to have a look at the folder structure on the server. Are you using multiple subdomains, top level domains, sub-folder off of a main domain, or a combination of any of those?

If you replace the contents of index.php with a simple piece of text, do both domains work?
