### ISSUE TITLE
I want use it 

### ISSUE THREAD

**Issue by vahidalvandi** [troychaplin79/wp-multitenant#5]
Hi . I want any tenant can login and show website self domain . And have secure website . Do this work?

**Comment by troychaplin** [comment]
Are you asking if you can have multiple sites that use their own domain name?

As far as security goes, I'm no expert but I think if this is setup outside the public folders it should be fine. I think the more important part is the security on the server and all the tenant installations.

**Comment by troychaplin** [comment]
No response, closing the issue
