### ISSUE TITLE
Each tenant have one database

### ISSUE THREAD

**Issue by vahidalvandi** [troychaplin79/wp-multitenant#6]
Do this project can create database for each tenant ?

**Comment by jimmycypherz** [comment]
Yes, you need to create a db per tenant.

**Comment by vahidalvandi** [comment]
Please create a boilerplate of video for fast test and run it .

**Comment by troychaplin** [comment]
Yes, each tenant has it's own database. There is a way you could use a single database but I don't see the point when multisite does that already.

Are you asking to have a video of a setup done? If so, unfortunately I do not have time to do that. But I do feel the setup instructions could be improved, hopefully soon.

**Comment by troychaplin** [comment]
No response, closing the issue
