### ISSUE TITLE
updated repository

### ISSUE THREAD

**Issue by luizsilva-dev** [troychaplin79/wp-multitenant#7]
I tried following the documentation and I couldn't get the domain to work.
I believe it's because some dependencies are outdated.
Is this repository active or do you have any other repository active?

error:
` Fatal error: Uncaught Dotenv\Exception\InvalidPathException: Unable to read any of the environment file(s) at [C:\Users\luizp\Documents\Projetos\www\wpteste\wp-multitenant\jalmeidapainting.com\.env]. in C:\Users\luizp\Documents\Projetos\www\wpteste\wp-multitenant\vendor\vlucas\phpdotenv\src\Loader.php:133 Stack trace: #0 C:\Users\luizp\Documents\Projetos\www\wpteste\wp-multitenant\vendor\vlucas\phpdotenv\src\Loader.php(91): Dotenv\Loader::findAndRead(Array) #1 C:\Users\luizp\Documents\Projetos\www\wpteste\wp-multitenant\vendor\vlucas\phpdotenv\src\Dotenv.php(123): Dotenv\Loader->load() #2 C:\Users\luizp\Documents\Projetos\www\wpteste\wp-multitenant\vendor\vlucas\phpdotenv\src\Dotenv.php(80): Dotenv\Dotenv->loadData() #3 C:\Users\luizp\Documents\Projetos\www\wpteste\wp-multitenant\jalmeidapainting.com\wp-env.php(19): Dotenv\Dotenv->load() #4 C:\Users\luizp\Documents\Projetos\www\wpteste\wp-multitenant\jalmeidapainting.com\wp-config.php(9): require_once('C:\\Users\\luizp\\...') #5 C:\Users\luizp\Documents\Projetos\www\wptes in C:\Users\luizp\Documents\Projetos\www\wpteste\wp-multitenant\vendor\vlucas\phpdotenv\src\Loader.php on line 133`

**Comment by troychaplin** [comment]
Hey @lpcs007, what does your directory structure look like? From the error log it leads me to believe you have your domain setup inside the multitenant installation area?

If so, that’s incorrect. The dir for multitenant and each domain being setup should all live at the same level.
