### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by yward** [troychaplin79/wp-multitenant#9]
Hello Troy,
Thank you for your hard work here and for sharing with the open-source community, the project is indeed superb.

I have one question though if possible.
How do we go about management?

I mean in a regular WordPress multisite, you'd just login as super admin to update plugins/add themes....etc

In this instance, there is no admin interface, so do I just replace the plugin folder to be updated when an update is due, or how does this work?

Thank you in advance.

**Comment by troychaplin** [comment]
Hey @yward, the versions of WP, themes and plugins in this project are managed with composer
